import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import {Theme} from "@radix-ui/themes";
import MobileNav from "@/components/MobileNav";
import DesktopNav from "@/components/DesktopNav";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import NotificationListener from "@/components/NotificationListener";
import { prisma } from "@/db";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {

  const session = await auth()

  
  console.log(session)
  const profile = await prisma.profile.findFirst({where: {
    email:  session?.user?.email || "" 
  }})



  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Theme>
          {modal}
          <div className="flex min-h-screen">
            <DesktopNav />
            <div className="pb-24 lg:pb-4 pt-4 px-4 lg:px-8 flex justify-around w-full">
              <div className="w-full">
                <NotificationListener recieverId={profile?.id ?? ""}  />
                {children}
              </div>
            </div>
          </div>
          <MobileNav />
        </Theme>

        <Toaster />

      </body>
    </html>
  );
}
